sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: i6jJ6BOxDKUCJXRmC3Zb5/qyKS7ZeTY8mVPXXjuvpiU994PzSgoNcL2FJ+9lyZ4VZb5NQbgYLabDRKJ51WpiPeEAbIaKYoggcTe8Ks8h4OcQjCqYxElWyXfwyefexp+XNVbnYaPRnTGn4/DmPf4L1F3sQvN8qGkOrWmN3eq3F2J1soPzZJD3oq/VdFIjf7HIIdSHHf005XgSQqpu2+VOqCdmgkXqxwDwxeXuoH3QCJ2BmEB/zajlJK9gTCrFclBL446/oVVFv1TENTEVlmJ6z8515Gtxm6+lOv+eRRUNxfadqmqi6Vjn6kDAayeQ3wpBlDZhipsLddv/uhJbcfLfd8MKPBLkYAhhGLgYyEn4u0A6zLjrUCvFg1fpZ05oMNO8OVRjc1H2n/oVKiKzPd7Gwbx8mkyA7ldTD4ex2jchPrIkdTZ63ruwu3FikNPyrTOcL5MRqJ3fUDM0VN+OisoaLVUXt7qRLgAAtqC4d6Csdtr7CEIh2hxw4nbV9IRpvxeF3SL2EZqVBb+1kBd3RD+3RXV4jNJUwzs6OFi0PD9w5Oc9RZRBlAjcwMN1E+dmjTGFSoOYTVy2KS47GOGi6L4XSIlK+yDaVPx8+xe/us1c+35Wdsvys2qDYVvL6Pz3abXLkATXHVKulPPYGKO5EYNYPOpqdo9Jn4ZdCDPQzObBDY4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/America-Through-the-Spectacles-of-an-Oriental-Diplomat_609
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy